### ISSUE TITLE
No response in Home app

### ISSUE THREAD

**Issue by bwdeleeuw** [NorthernMan54/homebridge-tcc#1]
Great project!

The thermostat seems to be connecting in the Homebridge screen, and pulling correct data and updates through tcc. However, in my Home app it continues to say 154F, and No Response. Any ideas?

![img_0400](https://cloud.githubusercontent.com/assets/7257240/19957989/e933a6b6-a160-11e6-9c2a-08b66df3e969.PNG)

![img_0401](https://cloud.githubusercontent.com/assets/7257240/19958027/30d34cc4-a161-11e6-9c97-a3d4489c356a.PNG)

**Comment by bwdeleeuw** [comment]
I found out that when I send the temperature back in Celsius instead of in Fahrenheit, the system works for me! 

I added lines 
`currentTemperature = (currentTemperature - 32) * 5/9`
and
`targetTemperature = (targetTemperature - 32) * 5 / 9`
to contend with this. I'm sure there are better ways to fix this.

Not sure if that is universal or not, but that might help someone. Thanks!

**Comment by NorthernMan54** [comment]
Question, what is logged from homebridge when the home app gets the data?  I'm using Celsius on my thermostat and in home kit.   I'm looking for these lines from the log

[11/3/2016, 7:17:01 PM] [Thermostat] Target temperature for Thermostat is 21°
[11/3/2016, 7:17:01 PM] [Thermostat] Current temperature of Thermostat is 21°
[11/3/2016, 7:17:01 PM] [Thermostat] Temperature unit for Thermostat is set to C

**Comment by bwdeleeuw** [comment]
before my change:
[11/3/2016, 5:53:27 PM] [Thermostat] Target temperature for Thermostat is 70°
[11/3/2016, 5:53:49 PM] [Thermostat] Current temperature for Thermostat is 70°
[11/3/2016, 5:53:49 PM] [Thermostat] Temperature unit for Thermostat is set to F

after my change:
[11/3/2016, 5:53:27 PM] [Thermostat] Target temperature for Thermostat is 21.666666666666668°
[11/3/2016, 5:53:49 PM] [Thermostat] Current temperature for Thermostat is 21.666666666666668°
[11/3/2016, 5:53:49 PM] [Thermostat] Temperature unit for Thermostat is set to F

And then the Home app show 70F, as expected.

Of  course, 70 C converts to 158 F, which is what first got me thinking. 

Hope that helps,

**Comment by NorthernMan54** [comment]
Tks

Just published a fix ( version 0.0.2), reinstall and let me know if it works.  I also fixed status updates as well.

**Comment by kenderson** [comment]
Just throwing a data-point in here. I just installed version 0.0.2 and am still seeing the "No Response" flag in the home app. The temp looks good on my end. Let me know if there's any other useful information that I can provide.

**Comment by NorthernMan54** [comment]
Ken can you share the log data, I'm wondering if there are other errors.

**Comment by bwdeleeuw** [comment]
@NorthernMan54,

Looking good! I'll leave the issue open for @kenderson, but my issue is resolved. 

Thanks!

**Comment by dbavatar** [comment]
Same issue. Seems to have something to do with the set temp. Set at 40F, actual 63F, reports 63F and "no response". Set temp to heat and 60F, it reports as actual 32F, and responds as set to "off". If it actually turn it off, reports as "cool", and it has no cool function.

**Comment by dbavatar** [comment]
[11/5/2016, 3:33:38 PM] [Garage] getTemperatureDisplayUnits
[11/5/2016, 3:33:38 PM] [Garage] Temperature unit for Garage is set to F
[11/5/2016, 3:33:38 PM] [Garage] Target temperature for Garage is 40°
[11/5/2016, 3:33:38 PM] [Garage] getTargetHeatingCooling
[11/5/2016, 3:33:38 PM] [Garage] getCurrentHeatingCooling
[11/5/2016, 3:33:38 PM] [Garage] Current Heating/Cooling state of Garage is 0
[11/5/2016, 3:33:38 PM] [Garage] Current temperature of Garage is 17.22222222222222°
[11/5/2016, 3:33:39 PM] [Garage] Target temperature for Garage is 40°
[11/5/2016, 3:33:52 PM] [Garage] Target temperature for Garage is 40°
[11/5/2016, 3:33:55 PM] [Garage] Target temperature for Garage is 40°
[11/5/2016, 3:33:56 PM] [Garage] Target temperature for Garage is 40°
[11/5/2016, 3:33:58 PM] [Garage] Target temperature for Garage is 40°
[11/5/2016, 3:33:58 PM] [Garage] Current relative humidity of Garage is 128%
...
[11/5/2016, 3:36:27 PM] [Garage] periodicUpdate
[11/5/2016, 3:36:29 PM] [Garage] getTargetHeatingCooling
[11/5/2016, 3:36:29 PM] [Garage] Target temperature for Garage is 60°
[11/5/2016, 3:36:29 PM] [Garage] getCurrentHeatingCooling
[11/5/2016, 3:36:29 PM] [Garage] Current Heating/Cooling state of Garage is 0
[11/5/2016, 3:36:29 PM] [Garage] getTemperatureDisplayUnits
[11/5/2016, 3:36:29 PM] [Garage] Temperature unit for Garage is set to F
[11/5/2016, 3:36:29 PM] [Garage] Current temperature of Garage is 17.22222222222222°
...
[11/5/2016, 3:36:35 PM] [Garage] Target temperature for Garage is 60°
[11/5/2016, 3:36:35 PM] [Garage] getCurrentHeatingCooling
[11/5/2016, 3:36:35 PM] [Garage] Current Heating/Cooling state of Garage is 0
[11/5/2016, 3:36:35 PM] [Garage] Current temperature of Garage is 17.22222222222222°
[11/5/2016, 3:36:35 PM] [Garage] getTemperatureDisplayUnits
[11/5/2016, 3:36:35 PM] [Garage] Temperature unit for Garage is set to F
[11/5/2016, 3:36:35 PM] [Garage] getTargetHeatingCooling

Logs don't seem to correspond 1:1 with what home app is reporting.

**Comment by bwdeleeuw** [comment]
Hi @kenderson, @dbavatar, could you try again with the latest master?

Either HomeBridge or HomeKit cannot work with a lower target temperature of 10C, 50F. Fix for now is to set the lowest target temperature to that number. Another idea would be to send that back to the thermostat as the setpoint, in order to keep things in sync.

Also, the messages should show results closer to the Home App.

I noticed that you have a result of 128% on the humidity. That seems to indicates that your thermostat cannot measure humidity. Is that correct?

**Comment by bwdeleeuw** [comment]
@NorthernMan54 could you publish release v0.0.4 for testing?

**Comment by dbavatar** [comment]
@bwdeleeuw Minimum temp fixes the no response issue for temp. Please don't automatically send it back to the thermostat. Setting for 40F is set for freeze protection, it's a perfectly valid setting.

You are correct I have no indoor humidity sensors. I do have an outdoor humidity/temp sensor on redlink with 5 thermostats on the same tcc account.

However "mode" can still cause no response:

[11/6/2016, 10:49:54 AM] [Master Bedroom] getCurrentHeatingCooling
[11/6/2016, 10:49:54 AM] [Master Bedroom] Current Heating/Cooling state of Master Bedroom is 3
[11/6/2016, 10:49:54 AM] [Master Bedroom] Current temperature of Master Bedroom is 71°
[11/6/2016, 10:49:54 AM] [Master Bedroom] getTemperatureDisplayUnits
[11/6/2016, 10:49:54 AM] [Master Bedroom] Temperature unit for Master Bedroom is set to F
[11/6/2016, 10:49:54 AM] [Master Bedroom] getTargetHeatingCooling
[11/6/2016, 10:49:54 AM] [Master Bedroom] Target temperature for Master Bedroom is 69°
[11/6/2016, 10:49:57 AM] [Master Bedroom] getCurrentHeatingCooling
[11/6/2016, 10:49:57 AM] [Master Bedroom] Current Heating/Cooling state of Master Bedroom is 3

All the modes:
real vs reported:
heat=heat (1)
drying=cool (2)
off=cool (2)
cool=no response (3)
auto=no response (4)

**Comment by NorthernMan54** [comment]
Latest version is published, I merged everything together and fixed a few bugs that crept in

I also added a 'debug' flag, so we can easily debug what is being returned in these cases.   I added it as an optional config.json parameter, details are in the README

**Comment by bwdeleeuw** [comment]
@NorthernMan54 good stuff!

Concerning the issue @dbavatar had with the modes:
My thermostat does not have a drying mode or an auto mode, so I cannot test that. My Off, Heat and Cool modes work perfectly. I'm wondering if TCC maintains a different numbering of modes if you have an additional Auto mode, but I cannot test that to confirm. My Model is: TH9320WF5003WW. If there are different numberings, we might be able to trigger off of the SwitchAutoAllowed property to correctly translate for different models. Shame there doesn't seem to be any documentation about this.

**Comment by dbavatar** [comment]
@bwdeleeuw Auto mode is probably hidden in your service menus. If it helps, I can get the html response dumps. I can try to code some of this stuff myself but I've never tried javascript before homebridge so I'm still feeling my way around.

Just tried the latest master, cool/heat mode display seems to work, but still displays wrong mode target temp, and it seems I have to restart homebridge to get it to change the status?

i.e. change from cool to heat via tcc portal, refresh homekit:
[11/6/2016, 11:33:38 PM] [Master Bedroom] getCurrentHeatingCoolingState is  null
[11/6/2016, 11:33:38 PM] [Master Bedroom] Target temperature for Master Bedroom is 20.555555555555557°
[11/6/2016, 11:33:38 PM] [Master Bedroom] Current temperature of Master Bedroom is 22.22222222222222°
[11/6/2016, 11:33:38 PM] [Master Bedroom] getTemperatureDisplayUnits
[11/6/2016, 11:33:38 PM] [Master Bedroom] Temperature unit for Master Bedroom is set to F
[11/6/2016, 11:33:38 PM] [Master Bedroom] getTargetHeatingCooling is  2

restart homebridge:

[11/6/2016, 11:34:11 PM] [Master Bedroom] getCurrentHeatingCoolingState is  null
[11/6/2016, 11:34:11 PM] [Master Bedroom] Target temperature for Master Bedroom is 19.444444444444443°
[11/6/2016, 11:34:11 PM] [Master Bedroom] Current temperature of Master Bedroom is 22.22222222222222°
[11/6/2016, 11:34:11 PM] [Master Bedroom] getTemperatureDisplayUnits
[11/6/2016, 11:34:11 PM] [Master Bedroom] Temperature unit for Master Bedroom is set to F
[11/6/2016, 11:34:11 PM] [Master Bedroom] getTargetHeatingCooling is  1

**Comment by bwdeleeuw** [comment]
@dbavatar it would probably be easier to pull the responses from the TCC site while manually change the modes with Chrome DevTools (F12), rather than pulling the html responses from HomeBridge, but if you are willing and able, that would go a long way to figuring out how to solve. I'll look into the auto status on my device, and see if that allows me to reproduce the issue.

**Comment by NorthernMan54** [comment]
I think the problem is that we are using heatsetpoint for the target temperature rather than coolsetpoint when in cool mode.

When I look at the data returned by my thermostat I see this

       HeatSetpoint: 21,
       CoolSetpoint: 25.5,

And when I switch to cool mode, the thermostat shows 25.5

**Comment by bwdeleeuw** [comment]
good point. 

I found an issue with the min/max, send a fix for your review.
Also added an initial version for the cool set point, which we did not have implemented yet. 

I'll be looking at sending back the correct set point when changing the mode.

**Comment by bwdeleeuw** [comment]
Found out that we can have Homekit display a range when in auto-mode! Hooking up the functions now.

**Comment by bwdeleeuw** [comment]
check out pull request #13 for the auto mode range.

**Comment by NorthernMan54** [comment]
@dbavatar Please try the latest version, completed wiring up of the 'cool' set points which should fix what you where seeing.

@bwdeleeuw I bundled all the changes together

Regarding thresholds, as my thermostat does not support Auto

SwitchAutoAllowed: false,

Going to have to add some logic to not display thresholds if the thermostat can't handle Auto

In this version I made some dramatic changes to periodic update, and removed all the if logic around determining what changed, and simply had it update all values.  As it is just using the cached device response, it is only a load on the homebridge side and not stressing the TCC servers.

Added logging in periodic update to show what values changed to, may offer further help in debugging issues.   Also need to capture what happens when TCC is not available.   Had my internet go down for a few hours today, and homebridge stopped updating the thermostat after the connection returned.   With no error messages ;-(

Wired get target temperature to look at the system switch position and read the appropriate set point.  When I flip the switch between Off, Heat and Cool I can now see the different set points.

**Comment by bwdeleeuw** [comment]
Hi @NorthernMan54,

sounds good. I'll have a chance to run through some testing later tonight.

**Comment by dbavatar** [comment]
@NorthernMan54 
1. Drag down to refresh does not work. Switching back to Home or re-opening favorites from control center does refresh. 

2. Heat/cool/auto display seems to work, but the set slider in auto mode seems to have problems with the absolute position displayed vs set, and also taking settings properly. Since it appears you don't have auto mode: Auto mode appears as a double sided slider, top and bottom, so you should be getting distinct heat/cool setpoints back from homekit

[11/9/2016, 9:56:52 PM] [Master Bedroom] Change  { latestData: { uiData: { HeatSetpoint: 68 } } }
[11/9/2016, 9:56:52 PM] [Master Bedroom] Target temperature for Master Bedroom is 10°
[11/9/2016, 9:56:52 PM] [Master Bedroom] Current temperature of Master Bedroom is 21.11111111111111°
[11/9/2016, 9:56:52 PM] [Master Bedroom] getCurrentHeatingCoolingState is  null
[11/9/2016, 9:56:52 PM] [Master Bedroom] getTargetHeatingCooling is  3
[11/9/2016, 9:56:52 PM] [Master Bedroom] Cool Setpoint temperature of Master Bedroom is 26.666666666666668°
[11/9/2016, 9:56:52 PM] [Master Bedroom] Heat Setpoint temperature of Master Bedroom is 20°
[11/9/2016, 9:57:49 PM] [Master Bedroom] periodicUpdate
[11/9/2016, 9:57:49 PM] [Master Bedroom] updateValues
[11/9/2016, 9:57:49 PM] [Master Bedroom] No change
[11/9/2016, 9:58:25 PM] [Master Bedroom] Setting target temperature for Master Bedroom to 21.6°
[11/9/2016, 9:58:26 PM] [Master Bedroom] Successfully changed temperature!
[11/9/2016, 9:58:26 PM] [Master Bedroom] { success: 1 }


3. The rate of update when changing temp I think is problematic. Is there a way to slow down updates from dragging the temp? I was locked out of my tcc account for a few minutes after sliding the temp slider.  

4. Looks like I can also make it crash while trying to turn down the slider under cool mode, this happens if you make several quick changes, probably an unknown response while getting rate limited by tcc?

[11/9/2016, 10:05:44 PM] Homebridge is running on port 51827.
[11/9/2016, 10:05:45 PM] [Master Bedroom] Target temperature for Master Bedroom is 26.666666666666668°
[11/9/2016, 10:05:45 PM] [Master Bedroom] getCurrentHeatingCoolingState is  null
[11/9/2016, 10:05:45 PM] [Master Bedroom] Cool Setpoint temperature of Master Bedroom is 26.666666666666668°
[11/9/2016, 10:05:45 PM] [Master Bedroom] Current temperature of Master Bedroom is 21.11111111111111°
[11/9/2016, 10:05:45 PM] [Master Bedroom] getTemperatureDisplayUnits
[11/9/2016, 10:05:45 PM] [Master Bedroom] Temperature unit for Master Bedroom is set to F
[11/9/2016, 10:05:45 PM] [Master Bedroom] getTargetHeatingCooling is  2
[11/9/2016, 10:05:45 PM] [Master Bedroom] Heat Setpoint temperature of Master Bedroom is 20°
[11/9/2016, 10:05:50 PM] [Master Bedroom] Setting target temperature for Master Bedroom to 22.2°
[11/9/2016, 10:05:51 PM] [Master Bedroom] Setting target temperature for Master Bedroom to 21°
[11/9/2016, 10:05:51 PM] [Master Bedroom] Setting target temperature for Master Bedroom to 23.4°
[11/9/2016, 10:05:52 PM] [Master Bedroom] Successfully changed temperature!
[11/9/2016, 10:05:52 PM] [Master Bedroom] { success: 1 }
undefined:1
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
^

SyntaxError: Unexpected token <
    at Object.parse (native)
    at Request._callback (/usr/local/lib/node_modules/homebridge-tcc/lib/tcc.js:141:35)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-tcc/node_modules/request/request.js:121:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-tcc/node_modules/request/request.js:978:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-tcc/node_modules/request/request.js:929:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)

3. Multiple thermostats stopped working, maybe because I'm getting rate limited. Second login for second thermostat freezes, probably need to enumerate or specify multiple thermostats per platform vs multiple logins.

@bwdeleeuw Let me know exactly which pages you would like me the capture. Grab me on gchat or something if that's easier. Same user @gmail

**Comment by NorthernMan54** [comment]
@dbavatar 

Answers to your comments

1: Drag down to refresh does not work. Switching back to Home or re-opening favorites from control center does refresh.

_When you do a refresh I'm just returning the lastest value from the cache, and the cache is updated every 60 seconds.   If you make a change at the thermostat or via the TCC App it won't show up for 60 seconds.  But it appears I fixed the original problem which was that you needed to restart homebridge to see updates.   Is the issue you are seeing the cache delay?_   

2: Heat/cool/auto display seems to work, but the set slider in auto mode seems to have problems with the absolute position displayed vs set, and also taking settings properly. Since it appears you don't have auto mode: Auto mode appears as a double sided slider, top and bottom, so you should be getting distinct heat/cool setpoints back from home kit

_At this time setting thresholds is not wired up yet, it will show but updates are ignored ;-(_

[11/9/2016, 9:56:52 PM] [Master Bedroom] Change { latestData: { uiData: { HeatSetpoint: 68 } } }
[11/9/2016, 9:56:52 PM] [Master Bedroom] Target temperature for Master Bedroom is 10°
[11/9/2016, 9:56:52 PM] [Master Bedroom] Current temperature of Master Bedroom is _21.11111111111111°_

Rounded this

[11/9/2016, 9:56:52 PM] [Master Bedroom] getCurrentHeatingCoolingState is **null**

_I'm thinking this null may be a latent issue, can you turn on the debug flag and post one set of results_ 

[11/9/2016, 9:56:52 PM] [Master Bedroom] getTargetHeatingCooling is 3
[11/9/2016, 9:56:52 PM] [Master Bedroom] Cool Setpoint temperature of Master Bedroom is 26.666666666666668°
[11/9/2016, 9:56:52 PM] [Master Bedroom] Heat Setpoint temperature of Master Bedroom is 20°
[11/9/2016, 9:57:49 PM] [Master Bedroom] periodicUpdate
[11/9/2016, 9:57:49 PM] [Master Bedroom] updateValues
[11/9/2016, 9:57:49 PM] [Master Bedroom] No change
[11/9/2016, 9:58:25 PM] [Master Bedroom] Setting target temperature for Master Bedroom to 21.6°
[11/9/2016, 9:58:26 PM] [Master Bedroom] Successfully changed temperature!
[11/9/2016, 9:58:26 PM] [Master Bedroom] { success: 1 }

3:The rate of update when changing temp I think is problematic. Is there a way to slow down updates from dragging the temp? I was locked out of my tcc account for a few minutes after sliding the temp slider.

_Noted, not fix yet_

4: Looks like I can also make it crash while trying to turn down the slider under cool mode, this happens if you make several quick changes, probably an unknown response while getting rate limited by tcc?

_S/b fixed_

[11/9/2016, 10:05:44 PM] Homebridge is running on port 51827.
[11/9/2016, 10:05:45 PM] [Master Bedroom] Target temperature for Master Bedroom is 26.666666666666668°
[11/9/2016, 10:05:45 PM] [Master Bedroom] getCurrentHeatingCoolingState is null
[11/9/2016, 10:05:45 PM] [Master Bedroom] Cool Setpoint temperature of Master Bedroom is 26.666666666666668°
[11/9/2016, 10:05:45 PM] [Master Bedroom] Current temperature of Master Bedroom is 21.11111111111111°
[11/9/2016, 10:05:45 PM] [Master Bedroom] getTemperatureDisplayUnits
[11/9/2016, 10:05:45 PM] [Master Bedroom] Temperature unit for Master Bedroom is set to F
[11/9/2016, 10:05:45 PM] [Master Bedroom] getTargetHeatingCooling is 2
[11/9/2016, 10:05:45 PM] [Master Bedroom] Heat Setpoint temperature of Master Bedroom is 20°
[11/9/2016, 10:05:50 PM] [Master Bedroom] Setting target temperature for Master Bedroom to 22.2°
[11/9/2016, 10:05:51 PM] [Master Bedroom] Setting target temperature for Master Bedroom to 21°
[11/9/2016, 10:05:51 PM] [Master Bedroom] Setting target temperature for Master Bedroom to 23.4°
[11/9/2016, 10:05:52 PM] [Master Bedroom] Successfully changed temperature!
[11/9/2016, 10:05:52 PM] [Master Bedroom] { success: 1 }
undefined:1
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
^

SyntaxError: Unexpected token <
at Object.parse (native)
at Request._callback (/usr/local/lib/node_modules/homebridge-tcc/lib/tcc.js:141:35)
at Request.self.callback (/usr/local/lib/node_modules/homebridge-tcc/node_modules/request/request.js:121:22)
at emitTwo (events.js:87:13)
at Request.emit (events.js:172:7)
at Request. (/usr/local/lib/node_modules/homebridge-tcc/node_modules/request/request.js:978:14)
at emitOne (events.js:82:20)
at Request.emit (events.js:169:7)
at IncomingMessage. (/usr/local/lib/node_modules/homebridge-tcc/node_modules/request/request.js:929:12)
at emitNone (events.js:72:20)
at IncomingMessage.emit (events.js:166:7)

5: Multiple thermostats stopped working, maybe because I'm getting rate limited. Second login for second thermostat freezes, probably need to enumerate or specify multiple thermostats per platform vs multiple logins.

_Future enhancement_

**Comment by bwdeleeuw** [comment]
@dbavatar 

here are the steps
1. Go to the Total Connect Comfort page in Chrome.
2. Log in, and connect to your thermostat.
3. Press F12 to bring up the DevTools
4. Click on the Network tab.
5. Change the thermostat mode and click Submit.
6. Click on the SubmitControlScreenChanges in the Network tab, scroll down to the Request Payload in the Headers. That should contain the information we are looking for. Each mode will result in a new Network call with a different PayLoad. Could you grab a Payload for each Mode change in your thermostat?

Thanks a bunch!

**Comment by NorthernMan54** [comment]
As we are into other issues now, am thinking we should close this and open new issues as needed.

**Comment by dbavatar** [comment]
@bwdeleeuw Sorry I missed that post, if it still helps:

Off:
{"DeviceID":520413,"SystemSwitch":2,"HeatSetpoint":null,"CoolSetpoint":null,"HeatNextPeriod":null,"CoolNextPeriod":null,"StatusHeat":null,"StatusCool":null,"FanMode":null}
Auto:
{"DeviceID":520413,"SystemSwitch":4,"HeatSetpoint":null,"CoolSetpoint":null,"HeatNextPeriod":null,"CoolNextPeriod":null,"StatusHeat":null,"StatusCool":null,"FanMode":null}
Cool:
{"DeviceID":520413,"SystemSwitch":3,"HeatSetpoint":null,"CoolSetpoint":null,"HeatNextPeriod":null,"CoolNextPeriod":null,"StatusHeat":null,"StatusCool":null,"FanMode":null}
Heat:
{"DeviceID":520413,"SystemSwitch":1,"HeatSetpoint":null,"CoolSetpoint":null,"HeatNextPeriod":null,"CoolNextPeriod":null,"StatusHeat":null,"StatusCool":null,"FanMode":null}
Set hold while in heat:
{"DeviceID":520413,"SystemSwitch":null,"HeatSetpoint":null,"CoolSetpoint":null,"HeatNextPeriod":null,"CoolNextPeriod":null,"StatusHeat":1,"StatusCool":1,"FanMode":null}
Change hold time to 10:15am:
{"DeviceID":520413,"SystemSwitch":null,"HeatSetpoint":null,"CoolSetpoint":null,"HeatNextPeriod":41,"CoolNextPeriod":41,"StatusHeat":null,"StatusCool":null,"FanMode":null}
Change hold time to 10:00am:
{"DeviceID":520413,"SystemSwitch":null,"HeatSetpoint":null,"CoolSetpoint":null,"HeatNextPeriod":40,"CoolNextPeriod":40,"StatusHeat":null,"StatusCool":null,"FanMode":null}
Switch to permanent hold:
{"DeviceID":520413,"SystemSwitch":null,"HeatSetpoint":null,"CoolSetpoint":null,"HeatNextPeriod":null,"CoolNextPeriod":null,"StatusHeat":2,"StatusCool":2,"FanMode":null}
Cancel hold:
{"DeviceID":520413,"SystemSwitch":null,"HeatSetpoint":null,"CoolSetpoint":74,"HeatNextPeriod":null,"CoolNextPeriod":null,"StatusHeat":0,"StatusCool":0,"FanMode":null}
Fan On:
{"DeviceID":1256152,"SystemSwitch":null,"HeatSetpoint":null,"CoolSetpoint":null,"HeatNextPeriod":null,"CoolNextPeriod":null,"StatusHeat":null,"StatusCool":null,"FanMode":1}
Fan Auto:
{"DeviceID":1256152,"SystemSwitch":null,"HeatSetpoint":null,"CoolSetpoint":null,"HeatNextPeriod":null,"CoolNextPeriod":null,"StatusHeat":null,"StatusCool":null,"FanMode":0}

Unfortunately I can't do anything with drying mode in the web portal, can't switch to it and it just shows "off". iOS app lets me change the temp in this mode and calls it "unknown"

**Comment by NorthernMan54** [comment]
@dbavatar
