### ISSUE TITLE
Locked out of TCC

### ISSUE THREAD

**Issue by rcenik** [NorthernMan54/homebridge-tcc#59]
It seems like the plugin spams the TCC site if you make too many adjustments the site will then lock you out and you get the login will failed. 

Maybe its possible to get the plugin added to the subscribed applications with TCC.

**Comment by rcenik** [comment]
It seems it still works even if you get the login failed message. maybe something to do with the data session. I don't know I'm not that good at coding. But this does work really good, thank you. 

Sample error below

5/6/2020, 9:05:15 PM Loaded plugin "homebridge-harmony".
5/6/2020, 9:05:15 PM Loaded plugin "homebridge-tcc".
5/6/2020, 9:05:15 PM [Arc] HarmonyPlatform Init
5/6/2020, 9:05:15 PM [Home] Logging into tcc...
5/6/2020, 9:05:15 PM [Arc] DidFinishLaunching
5/6/2020, 9:05:15 PM [Arc] (Arc)INFO - Loading activities...
5/6/2020, 9:05:15 PM [Arc] INFO - starting hub discovery
5/6/2020, 9:05:20 PM [Home] Logged into tcc! [
  {
    deviceID: '5416810',
    name: 'AC',
    usePermanentHolds: false,
    refresh: '120'
  },
  {
    deviceID: '5732915',
    name: 'Bedroom AC',
    usePermanentHolds: false,
    refresh: '120'
  }
]
5/6/2020, 9:05:21 PM [Home] Adding TCC Device Bedroom AC 5732915
5/6/2020, 9:05:21 PM [Arc] INFO - stopping hub discovery, hubs found : 10.0.0.33|Arc|5149764
5/6/2020, 9:05:21 PM [Arc] (Arc)INFO - received discovered hubs  10.0.0.33|Arc|5149764
5/6/2020, 9:05:22 PM [Home] Adding TCC Device AC 5416810
5/6/2020, 9:05:22 PM [Home] Initializing platform accessory "Bedroom AC"...
5/6/2020, 9:05:22 PM [Home] getServices Bedroom AC
5/6/2020, 9:05:22 PM [Home] Initializing platform accessory "AC"...
5/6/2020, 9:05:22 PM [Home] getServices AC
5/6/2020, 9:05:22 PM Bridge is running on port 51826.
5/6/2020, 9:05:22 PM [Arc] (Arc)INFO - Discovered Activity : Fire TV
5/6/2020, 9:05:22 PM [Arc] (Arc)INFO - Discovered Activity : TV-Switch
5/6/2020, 9:05:22 PM [Arc] (Arc)INFO - Discovered Activity : Xbox
5/6/2020, 9:06:02 PM [Home] Setting system switch for AC to 2
5/6/2020, 9:06:08 PM [Home] Successfully changed system!
5/6/2020, 9:06:08 PM [Home] { success: 1 }
5/6/2020, 9:06:08 PM [Home] Setting system switch for AC to 0
5/6/2020, 9:06:18 PM [Home] Successfully changed system!
5/6/2020, 9:06:18 PM [Home] { success: 1 }
5/6/2020, 10:07:29 PM [Home] Setting system switch for AC to 2
5/6/2020, 10:07:34 PM [Home] Successfully changed system!
5/6/2020, 10:07:34 PM [Home] { success: 1 }
5/6/2020, 10:07:35 PM [Home] Setting target temperature for AC to 22.8°
5/6/2020, 10:07:35 PM [Home] setHeatCoolSetpoint AC 0 1
5/6/2020, 10:07:35 PM [Home] Successfully changed temperature! AC { success: 1 }
5/6/2020, 10:07:35 PM [Home] Successfully changed temperature! { success: 1 }
5/6/2020, 10:07:42 PM [Home] Setting system switch for AC to 2
5/6/2020, 10:07:49 PM [Home] Successfully changed system!
5/6/2020, 10:07:49 PM [Home] { success: 1 }
5/6/2020, 10:07:49 PM [Home] Setting target temperature for AC to 31.1°
5/6/2020, 10:07:49 PM [Home] setHeatCoolSetpoint AC 0 1
5/6/2020, 10:07:50 PM [Home] Successfully changed temperature! AC { success: 1 }
5/6/2020, 10:07:50 PM [Home] Successfully changed temperature! { success: 1 }
5/6/2020, 10:07:54 PM [Home] Setting system switch for AC to 2
5/6/2020, 10:07:59 PM TCC Login Failed - POST null
5/6/2020, 10:07:59 PM 200
5/6/2020, 10:07:59 PM [Home] tcc Failed: TCC Login failed, please check your credentials
5/6/2020, 10:07:59 PM [Home] Setting target temperature for AC to 27.8°
5/6/2020, 10:07:59 PM [Home] setHeatCoolSetpoint AC 0 1
5/6/2020, 10:08:00 PM [Home] Successfully changed temperature! AC { success: 1 }
5/6/2020, 10:08:00 PM [Home] Successfully changed temperature! { success: 1 }
5/6/2020, 10:08:20 PM [Home] Setting target temperature for AC to 25.6°
5/6/2020, 10:08:20 PM [Home] setHeatCoolSetpoint AC 0 1
5/6/2020, 10:08:21 PM [Home] Successfully changed temperature! AC { success: 1 }
5/6/2020, 10:08:21 PM [Home] Successfully changed temperature! { success: 1 }
5/6/2020, 10:08:32 PM [Home] Setting system switch for AC to 0
5/6/2020, 10:08:38 PM [Home] Successfully changed system!
5/6/2020, 10:08:38 PM [Home] { success: 1 }
5/6/2020, 10:08:40 PM [Home] Setting system switch for Bedroom AC to 2
5/6/2020, 10:08:46 PM [Home] Successfully changed system!
5/6/2020, 10:08:46 PM [Home] { success: 1 }
5/6/2020, 10:08:51 PM [Home] Setting system switch for Bedroom AC to 2
5/6/2020, 10:08:59 PM [Home] Successfully changed system!
5/6/2020, 10:08:59 PM [Home] { success: 1 }
5/6/2020, 10:08:59 PM [Home] Setting system switch for AC to 0
5/6/2020, 10:09:03 PM TCC Login Failed - POST null
5/6/2020, 10:09:03 PM 200
5/6/2020, 10:09:03 PM [Home] tcc Failed: TCC Login failed, please check your credentials
5/6/2020, 10:09:16 PM [Home] Setting system switch for AC to 0
5/6/2020, 10:09:19 PM TCC Login Failed - POST null
5/6/2020, 10:09:19 PM 200
5/6/2020, 10:09:19 PM [Home] tcc Failed: TCC Login failed, please check your credentials
5/6/2020, 10:09:33 PM [Home] Setting system switch for Bedroom AC to 2
5/6/2020, 10:09:37 PM TCC Login Failed - POST null
5/6/2020, 10:09:37 PM 200
5/6/2020, 10:09:37 PM [Home] tcc Failed: TCC Login failed, please check your credentials
5/6/2020, 10:09:37 PM [Home] Setting target temperature for Bedroom AC to 25°
5/6/2020, 10:09:37 PM [Home] setHeatCoolSetpoint Bedroom AC 0 1
5/6/2020, 10:09:38 PM [Home] Successfully changed temperature! Bedroom AC { success: 1 }
5/6/2020, 10:09:38 PM [Home] Successfully changed temperature! { success: 1 }
5/6/2020, 10:09:52 PM [Home] Setting system switch for Bedroom AC to 2
5/6/2020, 10:09:55 PM TCC Login Failed - POST null
5/6/2020, 10:09:55 PM 200
5/6/2020, 10:09:55 PM [Home] tcc Failed: TCC Login failed, please check your credentials
5/6/2020, 10:09:56 PM [Home] Setting target temperature for Bedroom AC to 24.4°
5/6/2020, 10:09:56 PM [Home] setHeatCoolSetpoint Bedroom AC 0 1
5/6/2020, 10:09:57 PM [Home] Successfully changed temperature! Bedroom AC { success: 1 }
5/6/2020, 10:09:57 PM [Home] Successfully changed temperature! { success: 1 }

**Comment by NorthernMan54** [comment]
Am thinking that this issue is caused by your 2 devices and because I have never tested it.   Would you be able to share your login temporarily ( change your password, share it with me, I fix the issue, then you change the password to something else and lock me out )?   You can direct message me thru Discord to share.

**Comment by rcenik** [comment]
not sure how to use discord the PW is now your user name. let me know how it goes.

**Comment by rcenik** [comment]
you can also email me at rcenik@gmail.com

**Comment by NorthernMan54** [comment]
I have been running this over the last few days without issue……I’m kinda stuck as I thought that it was caused by your two devices causing issues.

**Comment by rcenik** [comment]
Have you tried making adjustments sequentially. It only happens if I make 4 or 5 adjustment within a few minutes.

**Comment by NorthernMan54** [comment]
Okay, are you okay with me tweaking your settings?  Did not want to cause a WAF issue

**Comment by rcenik** [comment]
No problem test as you need.

**Comment by NorthernMan54** [comment]
Thought I would give you a short status update.  After looking into the issue, need to change things up immensely and am reworking a lot of plugin code ( it needed it ).  Also switching from mimicking a browser to mimicking the mobile app ( simpler interface ).

So give me another week or so and should be done.

**Comment by mendeslr** [comment]
Thanks NorthernMan. I believe this is related to my problem to. I too also have 2 AC units controlled by a single TCC. The first command works but any succeeding commands fail. Thanks for re-working your code. I’ll be happy to test this issue when u are done.

**Comment by NorthernMan54** [comment]
Everyone, I have the new version ready for "Beta" testing.  If your comfortable being a tester, the command to install this version is this.   To rollback to the previous version, just install the regular version.

As this version auto discover's thermostat's and uses the name from TCC it may create duplicate thermostat's if you used a different name than TCC in the config file previously.

```
npm install -g github:NorthernMan54/homebridge-tcc#Mobile
```

Log from installation looks like this

```
npm WARN deprecated joi@13.7.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@5.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.

> node-expat@2.3.18 install /Users/nm/npm/lib/node_modules/homebridge-tcc/node_modules/node-expat
> node-gyp rebuild

  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
  LIBTOOL-STATIC Release/libexpat.a
  CXX(target) Release/obj.target/node_expat/node-expat.o
  SOLINK_MODULE(target) Release/node_expat.node
+ homebridge-tcc@0.2.0
added 56 packages from 98 contributors in 15.269s
```

**Comment by rcenik** [comment]
It seems to be working great, I will test more.

I could not get it to install on HOOBs, I kept getting an expat error on install. But it is working on Homebridge. I needed to use 

npm install -g --unsafe-perm github:NorthernMan54/homebridge-tcc#Mobile 

to install.

**Comment by dbavatar** [comment]
> Everyone, I have the new version ready for "Beta" testing. If your comfortable being a tester, the command to install this version is this. To rollback to the previous version, just install the regular version.
> 
> As this version auto discover's thermostat's and uses the name from TCC it may create duplicate thermostat's if you used a different name than TCC in the config file previously.
> 
> ```
> npm install -g github:NorthernMan54/homebridge-tcc#Mobile
> ```

Tried this out (had the thermostats moving the default room issue), it fails on adding the 3rd out of 5 thermostats. Also, names changed to all caps now?

[5/26/2020, 5:47:30 PM] [TCC] Adding TCC Device LIVING ROOM
[5/26/2020, 5:47:30 PM] [TCC] Adding TCC Device BEDROOM 2
[5/26/2020, 5:47:30 PM] [TCC] Adding TCC Device MASTER BEDROOM
pollThermostat Error: Cannot read property 'bind' of undefined
[5/26/2020, 5:47:30 PM] [TCC] Cannot read property 'bind' of undefined

Release branch working (device numbers removed):
[5/25/2020, 6:36:33 PM] [TCC] Adding TCC Device Master Bedroom XXXXXX
[5/25/2020, 6:36:34 PM] [TCC] Adding TCC Device Living Room XXXXXX
[5/25/2020, 6:36:34 PM] [TCC] Adding TCC Device Upper Level XXXXXX
[5/25/2020, 6:36:35 PM] [TCC] Adding TCC Device Bedroom 2 XXXXXX
[5/25/2020, 6:36:35 PM] [TCC] Adding TCC Device Garage XXXXXX

**Comment by NorthernMan54** [comment]
@dbavatar For the names, I now grab the names from TCC Website so you would need to adjust the names there.  I moved from the configuration file approach to auto configuring thermostats.

Can you share a DEBUG log for the error message?

Or conversely share your TCC Login so I can troubleshoot further?  ie send me a DM on Discord with your credentials after changing the password.

**Comment by dbavatar** [comment]
Sadly no new output after setting debug. I can just add you as a guest temporarily. What's your user/tag on discord? dbavatar#3699

**Comment by NorthernMan54** [comment]
I’m @NorthernMan54#6279 on the homebridge discord server

**Comment by rcenik** [comment]
I keep getting a polling error, the plugin still works fine.

[5/25/2020, 20:48:33] [Home] ERROR: pollDevices ERROR: GetLocations
pollThermostat Error: ERROR: GetLocations
[5/25/2020, 21:20:33] [Home] ERROR: pollDevices ERROR: GetLocations
pollThermostat Error: ERROR: GetLocations
[5/25/2020, 21:52:33] [Home] ERROR: pollDevices ERROR: GetLocations
pollThermostat Error: ERROR: GetLocations
[5/25/2020, 22:24:33] [Home] ERROR: pollDevices ERROR: GetLocations
[5/25/2020, 22:41:38] [Home] Setting switch for LIVING ROOM to 0
SOAP FAIL: Error: timeout of 3000ms exceeded
GetLocations Error: timeout of 3000ms exceeded
pollThermostat Error: timeout of 3000ms exceeded
[5/25/2020, 22:46:36] [Home] ERROR: pollDevices timeout of 3000ms exceeded
pollThermostat Error: ERROR: GetLocations
[5/25/2020, 23:17:33] [Home] ERROR: pollDevices ERROR: GetLocations
pollThermostat Error: ERROR: GetLocations
[5/25/2020, 23:48:33] [Home] ERROR: pollDevices ERROR: GetLocations
pollThermostat Error: ERROR: GetLocations
[5/26/2020, 00:19:33] [Home] ERROR: pollDevices ERROR: GetLocations
pollThermostat Error: ERROR: GetLocations
[5/26/2020, 00:50:33] [Home] ERROR: pollDevices ERROR: GetLocations
pollThermostat Error: ERROR: GetLocations
[5/26/2020, 01:22:33] [Home] ERROR: pollDevices ERROR: GetLocations
pollThermostat Error: ERROR: GetLocations
[5/26/2020, 01:53:33] [Home] ERROR: pollDevices ERROR: GetLocations
SOAP FAIL: Error: timeout of 3000ms exceeded
GetLocations Error: timeout of 3000ms exceeded
pollThermostat Error: timeout of 3000ms exceeded
[5/26/2020, 02:22:36] [Home] ERROR: pollDevices timeout of 3000ms exceeded
pollThermostat Error: ERROR: GetLocations
[5/26/2020, 02:53:33] [Home] ERROR: pollDevices ERROR: GetLocations
pollThermostat Error: ERROR: GetLocations
[5/26/2020, 03:25:33] [Home] ERROR: pollDevices ERROR: GetLocations
pollThermostat Error: ERROR: GetLocations
[5/26/2020, 03:57:33] [Home] ERROR: pollDevices ERROR: GetLocations
pollThermostat Error: ERROR: GetLocations
[5/26/2020, 04:28:35] [Home] ERROR: pollDevices ERROR: GetLocations
pollThermostat Error: ERROR: GetLocations
[5/26/2020, 05:00:33] [Home] ERROR: pollDevices ERROR: GetLocations
pollThermostat Error: ERROR: GetLocations
[5/26/2020, 05:31:33] [Home] ERROR: pollDevices ERROR: GetLocations
pollThermostat Error: ERROR: GetLocations
[5/26/2020, 06:02:33] [Home] ERROR: pollDevices ERROR: GetLocations
pollThermostat Error: ERROR: GetLocations
[5/26/2020, 06:33:33] [Home] ERROR: pollDevices ERROR: GetLocations
pollThermostat Error: ERROR: GetLocations
[5/26/2020, 07:04:33] [Home] ERROR: pollDevices ERROR: GetLocations
pollThermostat Error: ERROR: GetLocations
[5/26/2020, 07:35:33] [Home] ERROR: pollDevices ERROR: GetLocations
pollThermostat Error: ERROR: GetLocations
[5/26/2020, 08:06:34] [Home] ERROR: pollDevices ERROR: GetLocations
pollThermostat Error: ERROR: GetLocations
[5/26/2020, 08:38:33] [Home] ERROR: pollDevices ERROR: GetLocations
pollThermostat Error: ERROR: GetLocations
[5/26/2020, 09:09:34] [Home] ERROR: pollDevices ERROR: GetLocations
pollThermostat Error: ERROR: GetLocations
[5/26/2020, 09:40:34] [Home] ERROR: pollDevices ERROR: GetLocations
pollThermostat Error: ERROR: GetLocations
[5/26/2020, 10:11:34] [Home] ERROR: pollDevices ERROR: GetLocations
pollThermostat Error: ERROR: GetLocations
[5/26/2020, 10:42:34] [Home] ERROR: pollDevices ERROR: GetLocations
pollThermostat Error: ERROR: GetLocations
[5/26/2020, 11:14:34] [Home] ERROR: pollDevices ERROR: GetLocations
pollThermostat Error: ERROR: GetLocations
[5/26/2020, 11:45:34] [Home] ERROR: pollDevices ERROR: GetLocations
SOAP FAIL: Error: timeout of 3000ms exceeded
GetLocations Error: timeout of 3000ms exceeded
pollThermostat Error: timeout of 3000ms exceeded
[5/26/2020, 11:49:37] [Home] ERROR: pollDevices timeout of 3000ms exceeded
pollThermostat Error: ERROR: GetLocations
[5/26/2020, 12:20:34] [Home] ERROR: pollDevices ERROR: GetLocations
pollThermostat Error: ERROR: GetLocations
[5/26/2020, 12:51:34] [Home] ERROR: pollDevices ERROR: GetLocations
SOAP FAIL: Error: timeout of 3000ms exceeded
GetLocations Error: timeout of 3000ms exceeded
pollThermostat Error: timeout of 3000ms exceeded
[5/26/2020, 12:58:38] [Home] ERROR: pollDevices timeout of 3000ms exceeded
pollThermostat Error: ERROR: GetLocations
[5/26/2020, 13:29:34] [Home] ERROR: pollDevices ERROR: GetLocations
pollThermostat Error: ERROR: GetLocations
[5/26/2020, 14:00:34] [Home] ERROR: pollDevices ERROR: GetLocations
SOAP FAIL: Error: timeout of 3000ms exceeded
GetLocations Error: timeout of 3000ms exceeded
pollThermostat Error: timeout of 3000ms exceeded
[5/26/2020, 14:16:37] [Home] ERROR: pollDevices timeout of 3000ms exceeded
SOAP FAIL: Error: timeout of 3000ms exceeded
GetLocations Error: timeout of 3000ms exceeded
pollThermostat Error: timeout of 3000ms exceeded
[5/26/2020, 14:28:37] [Home] ERROR: pollDevices timeout of 3000ms exceeded
SOAP FAIL: Error: timeout of 3000ms exceeded
GetLocations Error: timeout of 3000ms exceeded
pollThermostat Error: timeout of 3000ms exceeded
[5/26/2020, 14:40:37] [Home] ERROR: pollDevices timeout of 3000ms exceeded
SOAP FAIL: Error: timeout of 3000ms exceeded
GetLocations Error: timeout of 3000ms exceeded
pollThermostat Error: timeout of 3000ms exceeded
[5/26/2020, 14:46:37] [Home] ERROR: pollDevices timeout of 3000ms exceeded
SOAP FAIL: Error: timeout of 3000ms exceeded
GetLocations Error: timeout of 3000ms exceeded
pollThermostat Error: timeout of 3000ms exceeded
[5/26/2020, 14:58:37] [Home] ERROR: pollDevices timeout of 3000ms exceeded
pollThermostat Error: ERROR: GetLocations
[5/26/2020, 15:29:36] [Home] ERROR: pollDevices ERROR: GetLocations
[5/26/2020, 15:46:37] [Home] Setting switch for LIVING ROOM to 2
pollThermostat Error: ERROR: GetLocations
[5/26/2020, 16:01:34] [Home] ERROR: pollDevices ERROR: GetLocations
[5/26/2020, 16:04:32] [Home] Setting switch for LIVING ROOM to 0
SOAP FAIL: Error: timeout of 3000ms exceeded
GetLocations Error: timeout of 3000ms exceeded
pollThermostat Error: timeout of 3000ms exceeded
[5/26/2020, 16:05:42] [Home] ERROR: pollDevices timeout of 3000ms exceeded
pollThermostat Error: ERROR: Login FailedAuthenticationFailed
[5/26/2020, 16:06:34] [Home] ERROR: pollDevices ERROR: Login FailedAuthenticationFailed
SOAP FAIL: Error: timeout of 3000ms exceeded
pollThermostat Error: timeout of 3000ms exceeded
[5/26/2020, 16:07:37] [Home] ERROR: pollDevices timeout of 3000ms exceeded
SOAP FAIL: Error: timeout of 3000ms exceeded
GetLocations Error: timeout of 3000ms exceeded
pollThermostat Error: timeout of 3000ms exceeded
[5/26/2020, 16:13:38] [Home] ERROR: pollDevices timeout of 3000ms exceeded
[5/26/2020, 16:16:08] [Home] Setting switch for LIVING ROOM to 2
pollThermostat Error: ERROR: GetLocations
[5/26/2020, 16:44:34] [Home] ERROR: pollDevices ERROR: GetLocations
SOAP FAIL: Error: timeout of 3000ms exceeded
GetLocations Error: timeout of 3000ms exceeded
pollThermostat Error: timeout of 3000ms exceeded
[5/26/2020, 16:49:37] [Home] ERROR: pollDevices timeout of 3000ms exceeded
pollThermostat Error: ERROR: GetLocations
[5/26/2020, 17:21:34] [Home] ERROR: pollDevices ERROR: GetLocations
SOAP FAIL: Error: timeout of 3000ms exceeded
GetLocations Error: timeout of 3000ms exceeded
pollThermostat Error: timeout of 3000ms exceeded
[5/26/2020, 17:25:37] [Home] ERROR: pollDevices timeout of 3000ms exceeded
pollThermostat Error: ERROR: GetLocations
[5/26/2020, 17:56:34] [Home] ERROR: pollDevices ERROR: GetLocations
pollThermostat Error: ERROR: GetLocations
[5/26/2020, 18:28:34] [Home] ERROR: pollDevices ERROR: GetLocations
SOAP FAIL: Error: timeout of 3000ms exceeded
GetLocations Error: timeout of 3000ms exceeded
pollThermostat Error: timeout of 3000ms exceeded
[5/26/2020, 18:37:37] [Home] ERROR: pollDevices timeout of 3000ms exceeded
SOAP FAIL: Error: timeout of 3000ms exceeded
GetLocations Error: timeout of 3000ms exceeded
pollThermostat Error: timeout of 3000ms exceeded
[5/26/2020, 19:07:37] [Home] ERROR: pollDevices timeout of 3000ms exceeded
pollThermostat Error: ERROR: GetLocations
[5/26/2020, 19:38:34] [Home] ERROR: pollDevices ERROR: GetLocations
SOAP FAIL: Error: timeout of 3000ms exceeded
GetLocations Error: timeout of 3000ms exceeded
pollThermostat Error: timeout of 3000ms exceeded
[5/26/2020, 19:53:37] [Home] ERROR: pollDevices timeout of 3000ms exceeded

**Comment by NorthernMan54** [comment]
@dbavatar I have fixed the issue you reported, so it should now install and work for you.  But I'm still working thru issues with changing the heating and cooling threshold temperature's in auto mode.  It should work okay if you just look at the settings.

@rcenik Still working on this, need a few more days

**Comment by dbavatar** [comment]
> I have fixed the issue you reported, so it should now install and work for you. But I'm still working thru issues with changing the heating and cooling threshold temperature's in auto mode. It should work okay if you just look at the settings.

Yes it finishes enumerating now. Still has some bugs though, getting errors and exclamations in home app. Will DM the log. Also strangely, it still shows all caps names even though I renamed everything in the portal - it shows properly in the browser and iOS app now.

**Comment by NorthernMan54** [comment]
@dbavatar @rcenik 

I think I'm almost done, if you can update to the latest test version and try again

```
npm install -g github:NorthernMan54/homebridge-tcc#Mobile
```

I think I have fixed all the issues, including the name issue.  Except with the names, HomeKit only accepts names when devices are created so any existing devices name won't update if changed in the portal.

In regards to the occasional errors, it should be more stable but I have noticed when running for an extended period of time that the portal has occasionally issue, but the plugin should reconnect.

**Comment by JimBobSD** [comment]
First, NorthernMan54 - you are the bomb.  Thanks for all your support on the various apps and most of all, making them past the wife-test :)

I've been having problems too (I have 3 TCC thermostats).  I installed the beta code and updated my config file to remove the three device IDs for the three thermostates.  Config file is JSON compliant.  But I'm getting the following errors now on startup.  Any ideas?

1|Homebridge-Thermostats  | [6/3/2020, 7:09:23 PM] ---
1|Homebridge-Thermostats  | [6/3/2020, 7:09:25 PM] Error: Error setting CharacteristicsProps for 'Target Temperature': 'minValue' cannot be greater or equal the 'maxValue'!
1|Homebridge-Thermostats  |     at Characteristic._this.setProps (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:429:15)
1|Homebridge-Thermostats  |     at new Characteristic (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:396:10)
1|Homebridge-Thermostats  |     at Function.Characteristic.deserialize (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:793:28)
1|Homebridge-Thermostats  |     at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:485:83
1|Homebridge-Thermostats  |     at Array.map (<anonymous>)
1|Homebridge-Thermostats  |     at Function.Service.deserialize (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:485:50)
1|Homebridge-Thermostats  |     at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1683:31
1|Homebridge-Thermostats  |     at Array.forEach (<anonymous>)
1|Homebridge-Thermostats  |     at Function.Accessory.deserialize (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1682:19)
1|Homebridge-Thermostats  |     at Function.deserialize (/usr/lib/node_modules/homebridge/src/platformAccessory.ts:150:33)
1|Homebridge-Thermostats  | [6/3/2020, 7:09:25 PM] Got SIGTERM, shutting down Homebridge...

**Comment by JimBobSD** [comment]
One more comment -- I also get these errors when installing:
pi@raspberrypi:~ $ sudo npm install -g --unsafe-perm github:NorthernMan54/homebridge-tcc#Mobile
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated joi@13.7.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@5.0.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.

> node-expat@2.3.18 install /usr/lib/node_modules/homebridge-tcc/node_modules/node-expat
> node-gyp rebuild

make: Entering directory '/usr/lib/node_modules/homebridge-tcc/node_modules/node-expat/build'
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
In file included from ../deps/libexpat/lib/xmltok.c:306:
../deps/libexpat/lib/xmltok_impl.c: In function ‘normal_isPublicId’:
../deps/libexpat/lib/xmltok_impl.c:1404:10: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if (!(BYTE_TO_ASCII(enc, ptr) & ~0x7f))
          ^
../deps/libexpat/lib/xmltok_impl.c:1406:5: note: here
     default:
     ^~~~~~~
../deps/libexpat/lib/xmltok_impl.c: In function ‘normal_sameName’:
../deps/libexpat/lib/xmltok_impl.c:1624:10: warning: this statement may fall through [-Wimplicit-fallthrough=]
       if (*ptr1++ != *ptr2++) \
          ^
../deps/libexpat/lib/xmltok_impl.c:1626:5: note: in expansion of macro ‘LEAD_CASE’
     LEAD_CASE(4) LEAD_CASE(3) LEAD_CASE(2)
     ^~~~~~~~~
../deps/libexpat/lib/xmltok_impl.c:1623:5: note: here
     case BT_LEAD ## n: \
     ^~~~
[AND THIS GOES ON AND ONE]

**Comment by NorthernMan54** [comment]
@JimBobSD The issue you reported is fixed, please try again

**Comment by NorthernMan54** [comment]
Everyone, I'm now going to publish this as the main version as all the bugs appear to have been worked out.

Thanks for your help in creating this new version and resolving these long standing issues
